apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec: 
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          image: IMAGE_TAG_PLACEHOLDER
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10